### ISSUE TITLE
Models do not load with the terrain.

### ISSUE THREAD

**Issue by ceearrbee** [Chevluh/Ultima-9-Blender-Importer#1]
Hello!

This is **amazing** and I've been playing with it. However, I have not been able to successfully get models to import with the terrain.

I've tried this in Blender 4.0 (which it doesn't seem to work with at all), and Blender 3.6 (which seems to work?) and when I go Import -> Ultima 9 terrain and import any .terrain files, I get the world and that is it.

I have added a screenshot of what I see (9.terrain)

![image](https://github.com/Chevluh/Ultima-9-Blender-Importer/assets/2192159/514b2394-53c2-4fbf-88b3-d30a93bfaa0f)

There are no errors in the console.

**Comment by Chevluh** [comment]
Hello

To load everything for a given map there are three steps. Say you want map 14 (which is much faster than 9 for a bug check while being decently populated), then you need to:

- import /static/terrain.14  with the _Ultima 9 terrain_ importer. This'll give you the terrain, similar to your screenshot
- import /static/fixed.14 with the _Ultima 9 models_ importer. This'll give you houses and trees and non-movable objects
- import /runtime/nonfixed.14 with the _Ultima 9 models_ importer. This'll give you the movable objects

Here's the result of those steps for me on Blender 4.0.1
![ultimap](https://github.com/Chevluh/Ultima-9-Blender-Importer/assets/99144592/3db7fedf-03ad-4c88-8f4a-b0769a2c1966)

There does seem to be a bug for the nonfixed file on map 9, which does bring up errors in the console, so I'll look into that. Loading buildings should work fine though.

**Comment by ceearrbee** [comment]
Thank you so much, I missed that completely. It look to be working now. :)
